### ISSUE TITLE
compile should add a carriage return to the end of content

### ISSUE THREAD

**Issue by mattkime** [smhg/gettext-parser#30]
this is nitpicky but nice to have - 

i'd like the output of `gettextParser.po.compile` to append a carriage return to its output. This is to reduce the number of lines shown in diffs after content is added. without the carriage return the last line in the previous version is always shown as changed since it didn't have the carriage return.

if there's agreement i'll go ahead and create a PR

**Comment by smhg** [comment]
I quickly checked what both GNU's xgettext and Poedit do when working with po files and both seem to either not append a carriage return or remove it if already present.
It sounds better to match their behavior I think.
I'll close the issue for now, but feel free to contradict.
