### ISSUE TITLE
Parse options

### ISSUE THREAD

**Issue by weeco** [smhg/gettext-parser#33]
Hello,
what about adding parse options like po2json has:

> fuzzy Whether to include fuzzy translation in JSON or not. Should be either true or false. Defaults to false.

**Comment by smhg** [comment]
This sounds like a good idea. Could you please provide a brief example of a PO with fuzzy translations and it's proposed JSON output? That would make a great test.
Thanks!

**Comment by smhg** [comment]
I'm going to close this for now, but please feel free to reopen when you have an example.

**Comment by juliomariano** [comment]
Still no solutions on this?

**Comment by smhg** [comment]
You can now support this development on IssueHunt:
https://issuehunt.io/r/smhg/gettext-parser/issues/33

Thank you!
