### ISSUE TITLE
Module not found: Error: Can't resolve 'stream' in '../node_modules/gettext-parser/lib/poparser.js`

### ISSUE THREAD

**Issue by coolstuffit** [smhg/gettext-parser#43]
Hi! 

This error appeared after updating @angular/cli 1.7 to 6.1.3.

I suggest to add `readable-stream` to dependencies and use it instead `stream` which is a mirror of the streams implementations in Node.js.

**Comment by smhg** [comment]
Fixed with #46. Thanks for reporting!
