### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by pronebird** [smhg/gettext-parser#49]
It's impossible to use the `gettext-parser` with TypeScript due to lack of annotations. It would be ace to add them.

**Comment by smhg** [comment]
What do you mean with impossible? It uses the JSDoc annotations, right? Do they contain errors?

**Comment by pronebird** [comment]
I don't know about that, but I see the error that tells me that the annotations file `.d.ts` is not found for `gettext-parser`.

**Comment by smhg** [comment]
I don't know enough about TypeScript to help you with this.
I'll close the now issue, but please feel free to (gather support to) submit a PR to add type declarations.
