### ISSUE TITLE
disabling line folding causes headers to break

### ISSUE THREAD

**Issue by lxg** [smhg/gettext-parser#58]
If the `gettextParser.po.compile` method is run with `{ foldLength : 0 }`, the headers will be written out in a single line, for example:

```
msgid ""
msgstr "Language: de_DE\nContent-Type: text/plain; charset=utf-8\nPlural-Forms: nplurals=2; plural=(n != 1);\n"
```

The reason is that in [pocompiler.js:224](https://github.com/smhg/gettext-parser/blob/master/lib/pocompiler.js#L224), the header block is prepared to be inserted as a normal msgid/msgstr, but if line wrapping is disabled, then it won’t become split up in [line 159](https://github.com/smhg/gettext-parser/blob/master/lib/pocompiler.js#L159).

A workaround is to set `{ foldLength: Number.MAX_SAFE_INTEGER }`, but ideally headers shouldn’t be broken when line wrapping is disabled.

**Comment by smhg** [comment]
Thank you for the report. This does not look right.
I'm not quite sure what the correct way to handle this is though? Are you expecting the header to always be folded (on line feeds)?

**Comment by lxg** [comment]
Yes, ideally they should be always folded, like this:

```
msgid ""
msgstr ""
"Language: de_DE\n"
"Content-Type: text/plain; charset=utf-8\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
```
I’m working with Gettext implementations since quite some time, and I have never seen it different, even when the messages themselves are unfolded.

However, to be honest, I don’t really know if the reported output is actually wrong, or just unusual.

I’m happy to provide a PR, if it helps.

**Comment by smhg** [comment]
Yes, it sounds reasonable. Especially when you specify a `foldLength` which is either longer than any header line or disable folding altogether (0).
I don't know what should happen when you specify something which is shorter than your longest header. In many ways it would make sense to fold _all_ `msgstr` instances (including header). I'd be surprised if that gets handled correctly though...

A PR would be very much appreciated. But I'd propose to only handle foldLength = 0 (fold on line feed). Don't change what happens when foldLength != 0. Because that might break too much (hard to estimate how people use this).

**Comment by lxg** [comment]
Yup, tricky one. I’ll try to come up with an implementation proposal and then we can then discuss at the code level. Might take a few days, though.

**Comment by lxg** [comment]
Hi, I now had a closer look at the code and tried to make the changes. However, I’m afraid I can’t really do it without potentially changing the previous behaviour. The reason is how the headers are preprocessed in the  `compile` function and then passed through to `_drawBlock` and then `_addPOString`. Due to the current flow and the assumptions it makes, my change would be a potentially breaking one.

I figured that for now, the workaroud based on the current behavious is probably fine. Maybe it’s worth documenting it … so if it turns out that I’m not the only person in the world with this problem, others can benefit from the workaround as well.

**Comment by smhg** [comment]
Thank you for the effort. It doesn't look like a simple change, indeed.
I'll leave this issue open for now, should anyone want to give it a try.

**Comment by KapitanOczywisty** [comment]
Original `--no-wrap` causes line breaks only on new line, thus breaks at new line should be always present.
