### ISSUE TITLE
Line break outputting incorrect format

### ISSUE THREAD

**Issue by sinnstudio-nas** [smhg/gettext-parser#66]
I am passing the following object to the po compiler

```
{
    msgctxt: '123',
    msgid: "This is a\r\nTest",
    msgstr: "This is a\r\nTest"
 }
```

and the result I get back is...

```
msgctxt "123"
msgid ""
"This is a\\r\\n"
"Test"
msgstr ""
"This is a\\r\\n"
"Test"
```

I believe the right format returned should be:

```
msgctxt "123"
msgid "This is a\\r\\nTest"
msgstr "This is a\\r\\nTest"
```

Is this the intended behavior?

**Comment by smhg** [comment]
This is new behaviour since 5.0.0. But only when you set `foldLength` to 0, right?

**Comment by sinnstudio-nas** [comment]
@smhg, I have not tried to mess with foldLength yet but this is a behavior since 4.2.0. I just upgraded to 5.0.0 and it's still the case. I will try foldLength and get back.

**Comment by sinnstudio-nas** [comment]
Just tried `const res = po.compile(out, {foldLength: 0}).` and I get the same result

**Comment by smhg** [comment]
@sinnstudio-nas I'm sorry, I mixed things up. This indeed has nothing to do with the recent changes (5.0.0).

Yes, line folding on newline characters seems to happen in any case.

Some thoughts:

- I think it would indeed be great to be able to configure line folding, as many different opinions seem to exists. And likely other options are necessary (as there are other characters on which folding happens).
- Maybe it is good to pull this into a separate library? With the `foldLength` option replaced by `folding` which will be passed on directly to the new library?

**Comment by sinnstudio-nas** [comment]
@smhg so maybe a `folding` object that has key and values like enabled and `foldLength`? That seems to be the better option here

**Comment by smhg** [comment]
Yes, that's it I think. But putting a line-folding package on npm doesn't sound too bad I think?
It has little to do with gettext-conversion and others might use it. Also, it would separate the tests (as they neither have anything to do with gettext).
Do you feel like giving this a try?

**Comment by sinnstudio-nas** [comment]
@smhg I would rather update the code here to account for all use cases for this project. Npm package may be a little heavy overtaking for me. Let me know your thoughts!

**Comment by smhg** [comment]
That's ok if you can put the folding-related tests in a separate folder please.

**Comment by sinnstudio-nas** [comment]
Solved with https://github.com/smhg/gettext-parser/pull/67
