### ISSUE TITLE
Version 5.0.0 seems to break Safari

### ISSUE THREAD

**Issue by edudipJens** [smhg/gettext-parser#69]
Hello there,

i recently upgraded the package in my Angular application from version 4.2.0 to 5.0.0. 
After that the Application did not start on both iOS and mac Safari anymore.

Angular version 13.2.4
Safari Version 15.2.

Browser console only said the following.
`SyntaxError: Invalid regular expression: invalid group specifier name`

**Comment by edudipJens** [comment]
Thank you for your answer.
It is a direct dependency of our project.

We are using it to parse .po files. 
Since we are planning to move our translations to .json files we can remove the package from the project. :)

**Comment by Delagen** [comment]
@smhg May be it can be simly ommited?
```
.split(/\\n/)
```
with later
```
for(let i=1;i<lines.length;i++)
 lines[i]=`\n${lines[i]`
```
