### ISSUE TITLE
Custom validation rules

### ISSUE THREAD

**Issue by vkhytskyi-allegro** [smhg/gettext-parser#75]
Hello :wave:

To start off I would like to thank you for developing and providing the library to the community!

I have a feature request. As a part of automation process of working with PO files I need to impose validation rules while parsing the files, like ensuring there are no duplicate `msgid`s or no entries with the same value for `msgstr`. The library already has a parser and a lexer, and I'd like to be able to reuse them for my particular needs. Two approaches come to my mind:

- the library exposes abovementioned entities as a part of public API,
- the library provides new API that would allow to define custom validation rules.

I'd like to learn you opinion and suggestions. Would you be willing to accept a PR?

**Comment by smhg** [comment]
Thank you for reaching out!
As I'm thinking of possible solutions, I think it would go pretty deep. And is there that much benefit?
You can now get any PO/MO object as a JSON structure. You an apply any rules on that and then pass it back to get your output as PO/MO.

Something like:
```javascript
import { po } from 'gettext-parser';
const data = po.parse(YOUR_INPUT);
// apply validation & changes
const output = po.compile(data);
```

This works for simple workflows, but maybe not for yours?

**Comment by smhg** [comment]
Don't get me wrong, your questions are very valid I think.
I didn't even realize the first `foo` in your example gets ignored. There is some room for improvement here.

First of all, specifically for PO-parsing, we'd need a bit of a restructure I think. Away from the current object-oriented style towards a functional approach. With accompanying tests.

We could then expose more parts alongside the current parse/compile methods.

Would you want to take a shot at this? If so, please send changes in small-ish chunks, with tests were feasible. That makes them easier to merge for me as I don't have huge amounts of time.

**Comment by vkhytskyi-allegro** [comment]
Hi @smhg! That's cool, I am open to take a look into it, although, I think that restructuring and changing the coding style (+ tests coverage) would require some time. Unfortunately, this is out of scope of my current task at hand. Do you see any possible short(er)-term solutions? What do you think about the validation rules I mentioned earlier? In your opinion, could any of them become a part of the library?

**Comment by vkhytskyi-allegro** [comment]
Hey @smhg, did you have a chance to take a look at my previous comment?

**Comment by smhg** [comment]
@vkhytskyi-allegro If not already the case, I'd say: fork it and add your requirements. Feel free to do it in a way that is easy to merge in the future. That gives me a better idea of what you need.
I definitely think something like this should be part of the library.

**Comment by smhg** [comment]
Thank you! I will try to have a look at it ASAP. It's great others are reviewing it already.
