### ISSUE TITLE
Support of Obsolete Messages

### ISSUE THREAD

**Issue by flozz** [smhg/gettext-parser#9]
Hello,

have you planned to support obsolete messages in your po parser?

Example of obsolete messages in a po file:

```
#~ msgid "Obsolete message"
#~ msgstr "Message obsolète"
```

regards,

**Comment by smhg** [comment]
Hi! I recently took over this project and I'm trying to follow up on open issues.
What do you expect as support? Passing them through while parsing/compiling?

**Comment by flozz** [comment]
Hello,

Thank you for your interest in this issue!

I mean just keep them in the Object generated after parsing the .po file, and write them down when converting the Object to a .po file.

Of course the obsolete message must not be kept when compiling to .mo

Regards,

**Comment by smhg** [comment]
@KapitanOczywisty thank you! It would be great to add this.
Would you be able to create a PR which includes tests for:

- whether converting from and to PO keeps track of these messages
- making sure they are not included in MO output
